### ISSUE TITLE
locationAlwaysAndWhenInUse returns didAllow when selecting 'Only While Using the App'

### ISSUE THREAD

**Issue by BrandonMHogan** [IvanVorobei/SPPermission#103]
Either this is a bug, or intended and I don't understand why. 

While using the locations permissions, the  **locationAlwaysAndWhenInUse** SPPermissionType will return as didAllow if you select the '_Only While Using the App_' option. It should only return true if '_Always Allow_' is selected.  Otherwise, what's the point of having  **locationWhenInUse** and **locationAlwaysAndWhenInUse** types?

**Comment by IvanVorobei** [comment]
Sorry for long response. Today I am release new version `3.0.6`, please, update. In this version bug fixed. Thanks!
