### ISSUE TITLE
Request:  Be able to theme the close button explicitly from SPPermissionDialogColorSource

### ISSUE THREAD

**Issue by sdnakhla** [IvanVorobei/SPPermission#104]
It would be great if you added properties that are specific to the close button to SPPermissionDialogColorSource.  I'd like to be able to theme it differently from the rest of the permission dialog so it stands out and is more obvious to the user.

**Comment by IvanVorobei** [comment]
Sorry for long response. Today I am release new version `3.0.6`, please, update. 
In this version available customise icon color. Also see `Readme`.
