### ISSUE TITLE
Add "AllowClosing" method to SPPermissionDialogDelegate

### ISSUE THREAD

**Issue by Xedart** [IvanVorobei/SPPermission#105]
Hello, first of all thank for this lib, it's really nice!

There are some scenarios where app cannot function without some permissions, for example my app must receive camera permission in order to do its work.
It would be very useful to add possibility to disallow closing of Permission Dialog by swiping it down.
Currently I have to do this in SPPermissionDialogDelegate:

@objc func didHide() {
        if !SPPermission.isAllowed(.camera) {
            SPPermission.Dialog.request(
                with: [.camera],
                on: self,
                delegate: self
            )
        }
    }

i.e. I just present Dialog whenever user closes it.

Would be nice to have something like this in SPPermissionDialogDelegate:

@objc func allowClosing() {
    return false
}

**Comment by IvanVorobei** [comment]
Good day! 

Delegate manipulation by events. For customize some properties or actions, see ‘SPPermissionDialogDataSource’. 

For you need set ‘dragEnabled’ to ‘false’. 

For more details, please, see ‘Readme’.

**Comment by Xedart** [comment]
Thank you for answer but if I set `dragEnabled` to `false`, the dialog can be closed by just tapping anywhere outside the dialog. Would be nice to have a possibility to change this behavior.

**Comment by IvanVorobei** [comment]
@Xedart I can add it, no problem. But you should know:

But you receive reject by apple. Request permission for all permissions can be skippable. I understand it sounds weird, but it’s so. 

You want add it?

**Comment by Xedart** [comment]
I didn't know that, this looks silly :) But ok, it means I'll have to implement some work around for it, and of course it doesn't make any sense to add this feature if apple rejects it.
Nevertheless thank you!
