### ISSUE TITLE
Some properties of SPPermissionDialogDataSource don't change anything

### ISSUE THREAD

**Issue by Xedart** [IvanVorobei/SPPermission#106]
There are some properties and methods in SPPermissionDialogDataSource that don't affect any appearance. They are:

`deniedTitle`
`deniedSubtitle`
`cancelTitle`
`settingsTitle`

Even though I have overridden them, nothing changed in UI

**Comment by IvanVorobei** [comment]
All work correctly. 
<img width="1010" alt="Screenshot 2019-05-06 at 14 09 02" src="https://user-images.githubusercontent.com/10995774/57221616-91391f80-7008-11e9-83d7-f7dfd345df17.png">

**Comment by Xedart** [comment]
Hmm, strange... But it doesn't work in my setup
Take a look:

<img width="1384" alt="Screen Shot 2019-05-06 at 14 41 35" src="https://user-images.githubusercontent.com/13368688/57222987-4077f580-700d-11e9-8ff5-b4f4bea12d73.png">


All others customizations work!

**Comment by IvanVorobei** [comment]
You can create simple project and send here link?

**Comment by Xedart** [comment]
Sure, here is my sample project:

[PermissionSample.zip](https://github.com/IvanVorobei/SPPermission/files/3151567/PermissionSample.zip)

Notice how just those 4 permissions don't work whilst all others do

**Comment by Xedart** [comment]
I figured out this issue, it was my fault, as I passed the `SPPermissionDialogDataSource` like this:

```swift
SPPermission.Dialog.request(
            with: [.camera],
            on: self,
            delegate: nil,
            dataSource: PermissionDialogDataSource()
        )
```

And of course delegate is not retained by SPPermission, so it should be created as property and passed like this:

```swift 

let permissionDataSource = PermissionDialogDataSource()

func presentPermissionDialog() {
        SPPermission.Dialog.request(
            with: [.camera],
            on: self,
            delegate: nil,
            dataSource: permissionDataSource
        )
    }
```

Now I works fine :)
