### ISSUE TITLE
Content doesn't update when coming back from settings

### ISSUE THREAD

**Issue by bilode** [IvanVorobei/SPPermission#107]
Steps:
- Tap an authorization switch
- Follow the link to the settings
- Modify the corresponding authorization
- Come back to the app

Observed behavior:
Corresponding switch doesn't update its state after the app comes back to the foreground

**Comment by IvanVorobei** [comment]
After change state of permission, app should reload.

**Comment by IvanVorobei** [comment]
@bilode which permission you use for it?

**Comment by bilode** [comment]
.notification and .locationAlwaysAndWhenInUse

**Comment by IvanVorobei** [comment]
@bilode I see app not reload for `.notification` & `.location...`.
It strange, for other permissions app reload after change state in settings.

I need some time for implement it.

**Comment by IvanVorobei** [comment]
I am upload new versions `3.0.8` with fix it. Please, update.

**Comment by KevinQuisquater** [comment]
Hi @ivanvorobei, this might be too much to ask but: when you notice that a permission has changed and therefore update the UI, could you also call the delegate method?
The UI is updated accordingly (it works great!), but the VC is not notified via the delegate method, so we cannot close the Dialog, for instance.
