### ISSUE TITLE
User selects "whenInUse" when prompted for locationAlwaysAndWhenInUse

### ISSUE THREAD

**Issue by bilode** [IvanVorobei/SPPermission#109]
If the user taps "whenInUse" when prompted for .locationAlwaysAndWhenInUse, the .locationAlwaysAndWhenInUse becomes neither allowed or denied (isAllowed(...) and isDenied(...) both return false)

This results in the requestDialog switch to be stucked on the "off" state and tapping it having no effect ; it doesn't show the native prompt because (counting as a "denied" for the OS I guess) and doesn't link to the settings either.

**Comment by IvanVorobei** [comment]
I am upload new versions `3.0.8` with fix it. Please, update.
