### ISSUE TITLE
Descriptions needs to fit longer text

### ISSUE THREAD

**Issue by rlaferla** [IvanVorobei/SPPermission#113]
Descriptions are currently limited to 2 lines.  It needs to be 3 lines long.  Two lines is not adequate to describe to the user why the permission is needed.

**Comment by IvanVorobei** [comment]
I think what need do lines by content. Auto for 2-3-10 lines if it need. 

I do it in next version. Maybe today.

**Comment by IvanVorobei** [comment]
I tested your request. While I can not implement it as the main branch - many users put the description in two lines. I would like to make an adaptive size, but this is not possible due to the multi-state button.

To solve the problem, I suggest you make a fork and set 3 lines (or more).
