### ISSUE TITLE
Disable unused APIs for App Store w/preprocessor macros

### ISSUE THREAD

**Issue by rlaferla** [ivanvorobei/SPPermission#115]
There should be preprocessor macros to configure which permissions are used by the application.  Otherwise, any application that uses SPPermission may get rejected by Apple's App Store because it uses frameworks that the application doesn't need/use.

**Comment by clay-mindoula** [comment]
Given my issue with submitting to the App store with unacceptable purpose strings rejects. This lloks like it going to become a bigger issue.

**Comment by ivanvorobei** [comment]
@rlaferla maybe you can help me implement it?

**Comment by ivanvorobei** [comment]
I am upload new version `4.0`. Please, update. 
Also see `Readme` for integrate need modules.
