### ISSUE TITLE
[Request] Ability to customize the fonts and ALLOW button colors

### ISSUE THREAD

**Issue by anthonycastelli** [ivanvorobei/SPPermission#116]
Is there a way we can get access to change the fonts and font sizes for the entire view? My app uses a custom font and id like to be able to keep the same style and match things together. 

As for the "Allow" button, is it possible to change the selected and non-selected colors?

**Comment by IvanVorobei** [comment]
@anthonycastelli for now can't customise font.
For customise color see `SPPermissionDialogColorSource`.

You really need customise font?
