### ISSUE TITLE
App Store reject due to unacceptable NSAppleMusicUsageDescription purpose string

### ISSUE THREAD

**Issue by clay-mindoula** [ivanvorobei/SPPermission#120]
Apple is rejecting my app because it doesn't accept my NSAppleMusicUsageDescription purpose string. Is there a "good" Apple acceptable purpose string I can use. Trying "Is used to manage permissions conveniently for you" right now. 

I'm not using Music just the SPPermissions pod.

**Comment by clay-mindoula** [comment]
I'm stuck it seems and can't generate an acceptable string.

**Comment by ivanvorobei** [comment]
For usage pod need add string in plist for all permission. 
I am try do now macros for extension code.

**Comment by clay-mindoula** [comment]
I have strings for all necessary permissions. It just the music permission and given what Apple are about to release it seems likely they are locking down this permission in particular.

**Comment by ivanvorobei** [comment]
@clay-mindoula it happen because your app usage requests permission with my pod. Now I fixing it.

**Comment by clay-mindoula** [comment]
I understand this. Please let me know if I can be of assistance!

**Comment by ivanvorobei** [comment]
It will be today.

**Comment by ivanvorobei** [comment]
I am upload new version `4.0`. Please, update. 
Also see `Readme` for integrate need modules.

**Comment by clay-mindoula** [comment]
just confirming either my hacking out NSAppleMusicUsageDescription and your updates both stopped the app being rejected
