### ISSUE TITLE
SPPermission not able to check for permissions

### ISSUE THREAD

**Issue by davidvpe** [ivanvorobei/SPPermission#121]
When calling the function hasPermission() the console shows this error

`Fatal error: SPPermission - Camera not import. See Readme: https://github.com/ivanvorobei/SPPermission`

I am aware of the situation with the permissions and Apple's new policy. But I am using Carthage and in SPPermission Readme doesn't say that I have to do anything extra. Is there any way to solve this issue?

**Comment by ivanvorobei** [comment]
I am try update `Carthage` and now it will be work. 
If not work, please, write me.

**Comment by ivanvorobei** [comment]
Also see updated `Readme` about configuration file.

**Comment by davidvpe** [comment]
It works now. Amazing! didn't know you can create hooks like that Thanks x1000

**Comment by ivanvorobei** [comment]
@davidvpe no problem) Thanks for issue!

**Comment by ivanvorobei** [comment]
@davidvpe for now with `Carthage` asset problem, you can test?

**Comment by KrLikeblue** [comment]
I have added your project Manually and I am getting this error.

Please can you help me ?

**Comment by ivanvorobei** [comment]
@KrLikeblue see example project. You need add configuration

**Comment by KrLikeblue** [comment]
Hello, I have added configuration file

But still getting error

**Comment by ivanvorobei** [comment]
@KrLikeblue you set configuration in project settings? Maybe not.

**Comment by KrLikeblue** [comment]
In project settings ???? I did not understand. Can you post some photo ? 

I added configuration file by going into File -> New -> File ->Configuration Setting File.

Let me know if I am missing something

**Comment by ivanvorobei** [comment]
@KrLikeblue 
<img width="823" alt="Screenshot 2019-08-14 at 13 16 50" src="https://user-images.githubusercontent.com/10995774/63013814-ca015400-be95-11e9-9bd2-f29ddf82aeb6.png">

**Comment by KrLikeblue** [comment]
Awesome Man....!!! Solved it...

But why it is required ?? can you please explain.. I am new to this

By the way. Thank you very much...
Thanks

**Comment by ivanvorobei** [comment]
> Due to Apple's new policy regarding permission access you need to specifically define what kind of permissions you want to access using subspecs.

Apple check which permissions you trying request and can reject app. Need use submodules.

**Comment by ajjumehra** [comment]
Not working with SPM

**Comment by varabeis** [comment]
@ajjumehra true, still
