### ISSUE TITLE
Requesting contacts results in Contacts Not Import error

### ISSUE THREAD

**Issue by mrferris** [ivanvorobei/SPPermission#123]
Hi, I am running **version 4.0.0,** and when I call the following code, I get the following error. This code works fine and does not produce an error on version 3.0.5. 

Code:

`if !SPPermission.isAllowed(.contacts){...}`

Error:

`Status [10:0x0]: 1:57Fatal error: SPPermission - Contacts not import. See Readme: https://github.com/ivanvorobei/SPPermission: file 
SourceCode/iOS/ios-client/Pods/SPPermission/Source/SPPermission/SPPermission.swift, line 107 `

**Comment by ivanvorobei** [comment]
You install via pods?

**Comment by ivanvorobei** [comment]
@mrferris any info?

**Comment by cukingpro** [comment]
I have the same issue with photo library permission. Fatal error: SPPermission - Photo Library not import.

**Comment by cukingpro** [comment]
I install via cocoapods.

**Comment by ivanvorobei** [comment]
@cukingpro please attach your pod file

**Comment by cukingpro** [comment]
[Podfile.zip](https://github.com/ivanvorobei/SPPermission/files/3375484/Podfile.zip)
I'm using SPPermission 4.0.5

**Comment by markangelohernandez** [comment]
Same issue with location and notification permission using version 4.0.5.
Here are the error logs:
```
Fatal error: SPPermission - Location Always not import. See Readme: https://github.com/ivanvorobei/SPPermission
```

```
Fatal error: SPPermission - Notification not import. See Readme: https://github.com/ivanvorobei/SPPermission
```

**Comment by ivanvorobei** [comment]
@cukingpro please, see Readme file. Section installation. You need install module.

**Comment by ivanvorobei** [comment]
@markangelohernandez you install via module? Please, see Readme (This is written in error, you see?)
