### ISSUE TITLE
Terminated due to signal 9

### ISSUE THREAD

**Issue by furiosFast** [ivanvorobei/SPPermission#125]
Hello,
the demo app crashes with the following error: 
`Message from debugger: Terminated due to signal 9`
when returning from the iOS settings app after enabling / disabling the photo library permission

**Comment by ivanvorobei** [comment]
Hi! 
It not bug. After change permission state in settings app remove from memory (close in simulator). When you open app after change state any permission (exclude notification) - app reload.

**Comment by furiosFast** [comment]
ok, thanks
