### ISSUE TITLE
NSPhotoLibraryAddUsageDescription

### ISSUE THREAD

**Issue by furiosFast** [ivanvorobei/SPPermission#126]
Hi,
is NSPhotoLibraryAddUsageDescription supported?

**Comment by ivanvorobei** [comment]
Hi, yes

**Comment by ivanvorobei** [comment]
All sported permissions you can see [here](https://github.com/ivanvorobei/SPPermission#permissions)

**Comment by furiosFast** [comment]
where is he here?: https://github.com/ivanvorobei/SPPermission/blob/master/Source/SPPermission/SPPermissionType.swift

**Comment by ivanvorobei** [comment]
Hmmm
Maybe this))
```swift
case .photoLibrary:
```

**Comment by furiosFast** [comment]
i've this:
`SPPermission.Dialog.request(with: [.locationWhenInUse, .notification, .photoLibrary/*, .microphone*/], on: viewController, delegate: self, dataSource: self)`
but che function 
`SPPermission.isAllowed(.photoLibrary)
`return false always

**Comment by ivanvorobei** [comment]
I am now run example and all work correctly. You can send me simple example project for see? Or all code which you use.

**Comment by furiosFast** [comment]
i've this function in my app:
```
func simplePhotoViewerController(_ viewController: SimplePhotoViewerController, savePhotoAt index: Int) {
        guard let img = cartina.image else { return }
        UIImageWriteToSavedPhotosAlbum(img, nil, nil, nil)
        //        share(UIButton())
        if SPPermission.isAllowed(.photoLibrary) {
            SCLAlertView(appearance: SCLAlertView.SCLAppearance(dynamicAnimatorActive: true)).showSuccess("", subTitle: loc("IMAGESAVE"))
        } else {
            let alert = SCLAlertView(appearance: SCLAlertView.SCLAppearance(dynamicAnimatorActive: false))
            alert.addButton(loc("settings_TITLEPAGE")) {
                UIApplication.shared.open(URL.init(string: UIApplication.openSettingsURLString)!, options: [:], completionHandler: nil)
            }
            alert.showCustom(loc("permissionPREMISSIONDENIED"), subTitle: loc("permissionGOTO"), color: UIColor(hexString: "#0xFFD110"), closeButtonTitle: loc("permissionCANCEL"), colorTextButton: 0x000000, style: .warning)
        }
    }
```
and when i go to save the photo, if in setting app the photo permission for the app is set to "never", my app terminate with this error: 

> 2019-07-29 21:21:00.057206+0200 iWindRose[4781:227005] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.> (lldb) 
if i add the NSPhotoLibraryAddUsageDescription in info.plist, and i set from settings app the photo permission on "Add photo only", the function 
`SPPermission.isAllowed(.photoLibrary)`
return false

**Comment by ivanvorobei** [comment]
How you request permission?

**Comment by furiosFast** [comment]
```
func presentPermissonDialogFromWelcomeView(_ viewController: UIViewController) {
        SPPermission.Dialog.request(with: [.locationWhenInUse, .notification, .photoLibrary/*, .microphone*/], on: viewController, delegate: self, dataSource: self)
    }
```

**Comment by furiosFast** [comment]
Is this the case with the authorization .restricted?

**Comment by ivanvorobei** [comment]
What is case `Add photo only`? In permission state has only this. 
<img width="378" alt="Screenshot 2019-07-29 at 22 30 04" src="https://user-images.githubusercontent.com/10995774/62076501-7e716800-b250-11e9-850b-a7d651b543f1.png">

I am try using your code - all work correct. When you call `simplePhotoViewerController`? After request permission? Show code.

**Comment by furiosFast** [comment]
now set the permission to "never" and try to call this line of code with a button:
```
guard let img = imageView.image else { return }
UIImageWriteToSavedPhotosAlbum(img, nil, nil, nil)
```

**Comment by ivanvorobei** [comment]
It code not should work. `Never` state restricted permission to Photo Lubrary.

**Comment by furiosFast** [comment]
> What is case `Add photo only`? In permission state has only this.
> <img alt="Screenshot 2019-07-29 at 22 30 04" width="378" src="https://user-images.githubusercontent.com/10995774/62076501-7e716800-b250-11e9-850b-a7d651b543f1.png">
> 
> I am try using your code - all work correct. When you call `simplePhotoViewerController`? After request permission? Show code.

Yes, i request permission at the first launch of my app

**Comment by ivanvorobei** [comment]
If you deny access to the Photo Library (set `Never` state), then of course the function `isAllow` will return false.

**Comment by ivanvorobei** [comment]
Also function `UIImageWriteToSavedPhotosAlbum` complete, but with error in completion.

**Comment by furiosFast** [comment]
if you set to "never" the permission and try again to save the photo, the app crash with this error:

> This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by ivanvorobei** [comment]
> if you set to "never" the permission and try again to save the photo, the app crash with this error:
> 
> > This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

My library is not responsible for this.

**Comment by ivanvorobei** [comment]
So one sec
I found this

`NSPhotoLibrary - ADD - UsageDescription `

**Comment by furiosFast** [comment]
yes, NSPhotoLibraryAddUsageDescription

**Comment by ivanvorobei** [comment]
<img width="672" alt="Screenshot 2019-07-29 at 22 41 47" src="https://user-images.githubusercontent.com/10995774/62077173-20458480-b252-11e9-805f-a2186d7ca51f.png">

I am use `NSPhotoLibraryUsageDescription` for both, all ok. 

As I understand it, when you change the resolution in the settings, do you get an error when saving? But my library does not participate in these actions, you need to look for another reason.

**Comment by furiosFast** [comment]
OK thanks

**Comment by ivanvorobei** [comment]
Also I am record video - all changes see correctly. Add only `NSPhotoLibraryUsageDescription`.
[Screen Recording 2019-07-29 at 22.45.20.zip](https://github.com/ivanvorobei/SPPermission/files/3444048/Screen.Recording.2019-07-29.at.22.45.20.zip)

**Comment by furiosFast** [comment]
thanks again!!
