### ISSUE TITLE
how to localize SPPermission text?

### ISSUE THREAD

**Issue by bizibizi** [ivanvorobei/SPPermission#131]

**Comment by ivanvorobei** [comment]
Hi. 
See [Readme](https://github.com/ivanvorobei/SPPermission#texts), sections `Texts`

**Comment by bizibizi** [comment]
can not localize:

        case .notification:
            return "Notification"
        case .microphone:
            return "Microphone"
        case .calendar:
            return "Calendar"
        case .contacts:
            return "Contacts"
        case .reminders:
            return "Reminders"
        case .speech:
            return "Speech"
        case .locationWhenInUse:
            return "Location When Use"
        case .locationAlwaysAndWhenInUse:
            return "Location Always"
        case .motion:
            return "Motion"
        case .mediaLibrary:
            return "Media Library"
