### ISSUE TITLE
SPPermission - Location When Use not import

### ISSUE THREAD

**Issue by nickpali** [ivanvorobei/SPPermission#135]
I keep getting the error message 
`SPPermission - PERMISSON-NAME not import`

I read the readme, I'm installing using pods and my podfile has these
`
  pod 'SPPermission/Notification'
  pod 'SPPermission/Location'
`

What else do I need to do?

**Comment by ivanvorobei** [comment]
@nickpali hi! 
Please, archive Xcode project with installing pods and send me. 

I add for empty project this pods and all work correct.

**Comment by nickpali** [comment]
I was able to fix this issue by first uninstalling SPPermission. Deleting all of the pods and re-installing. I think this happened as I used to just have `pod SPPermission` and I didnt uninstall it first before installing the new separate pods.
