### ISSUE TITLE
Ios 13 problem

### ISSUE THREAD

**Issue by alxrguz** [ivanvorobei/SPPermission#136]
Hi Ivan, first of all I want to say thanks for your work.
While developing the application, I found a bug on ios 13 (maybe I did something wrong). I invoke a request at the click of a button, with the nabigationBar remaining on top of the BlurView. On ios 11 and 12, this problem is not observed
You can see example on yandex disk - https://yadi.sk/i/h6grgosSFZDUGw

**Comment by ivanvorobei** [comment]
On which controller you present `SPPermission`?

**Comment by alxrguz** [comment]
In `viewDidLoad` I set up `navigationController`, set the buttons, title, color, then in `viewDidAppear` I present `SPPermission`
```
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        documentTableView.reloadData()
        DispatchQueue.main.asyncAfter(deadline: .now() + 2){
            if UserDefaults.standard.bool(forKey: "com.permission") == false {
                SPPermission.Dialog.request(
                    with: [.photoLibrary, .camera, .notification],
                    on: self,
                    delegate: self,
                    dataSource: self
                )
                //interim solution
                self.navigationController?.setNavigationBarHidden(true, animated: true)
                UserDefaults.standard.set(true, forKey: "com.permission")
            }
        }
    }
```
and when button tapped I'm doing a check again and present SPPermission (if user denied permissions)
```
@objc private func createScanTapped(_ sender: UIButton){
        if !SPPermission.isAllowed(.camera) || !SPPermission.isAllowed(.photoLibrary){
            SPPermission.Dialog.request(
                with: [.photoLibrary, .camera],
                on: self,
                delegate: self,
                dataSource: self
            )
    }
}
```

**Comment by ivanvorobei** [comment]
You need present SPPermission on `navigation` controller. If you present of child - blur only child. Need pass top controller for blur full size of it controller. I think it help for you.

**Comment by alxrguz** [comment]
Thank you very much for your help, I will leave my solution for the rest
```
let view = self.navigationController ?? self
SPPermission.Dialog.request(
                with: [.photoLibrary, .camera],
                on: view,
                dataSource: self)
```
