### ISSUE TITLE
[SUGGESTION] - Carthage

### ISSUE THREAD

**Issue by maclacerda** [IvanVorobei/SPPermission#32]
Hello,

It's possible add the Carthage support on your Library ?

Thanks

**Comment by jojo91** [comment]
+1

**Comment by Droppix** [comment]
+1

**Comment by kirillrybin** [comment]
+1

**Comment by sverin** [comment]
@IvanVorobei Any chance to release the version with carthage support?

**Comment by IvanVorobei** [comment]
@sverin, I tried to figure out how to add support, but I did not succeed. I hope that someone will be able to suggest how to do it and I will release a version

**Comment by sverin** [comment]
@IvanVorobei 

To add support for Carthage for your existing library you need to share the scheme of your project. To do that you have to:

Open the workspace.
Go to Product > Scheme > Manage Schemes.
Select the Shared checkbox for your scheme

Test if the scheme builds successfully by running `carthage build --no-skip-current`.

You also need to commit the `SPPermission.xcodeproj` file. All files in the project should be commited.
If the build still fails, uncheck the the shared scheme and check it again.

**Comment by IvanVorobei** [comment]
@sverin, thanks! I think I understood... The map file implies that my library will be part of the scheme. Is there an opportunity for the map file to specify only the package with the source files? No in project `SPPermission` all resources files place in `/source` folder

**Comment by toftof** [comment]
hi, hope you you can release Carthage support soon. Love this framework

**Comment by IvanVorobei** [comment]
Good day friends! 

Now I am work about ‘Carthage’! 🔥
But it first publish and I am need testing period... please, after publish, testing it. 

Thanks, dear friends!

**Comment by IvanVorobei** [comment]
Friends, I am added support `Carthage`. You can test it now. If you find any bugs, please, create new issue. Thanks!
