### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by FlorolF1** [IvanVorobei/SPPermission#61]
Reproduce: Presenting SPRequest.Dialog -> Denie access (e.g. for camera) -> you will not see the altert to get directed to settings.

This worked with the last version.

**Comment by FlorolF1** [comment]
You can fix it with the dialog

**Comment by IvanVorobei** [comment]
Please, describe more

**Comment by IvanVorobei** [comment]
Oh, I undestand... I will added it new version, and now now close this issue. Thanks!

**Comment by FlorolF1** [comment]
(y) thank you.
Btw. do your code provide any kind of completion handler?! 
E.g. you want to build a camera application (camera is initial view controller). The normal way is to ask for permission in ViewDidLoad (If PermissionStatus is .notAuthorized you won't **configure the session**). In ViewDidAppear you do the same thing and **start the session** if the permission is authorized. 
In order to use your code (bzw. really nice design (y)) i need a completion handler to implement PermissionDialog in ViewDidAppear method. Do your code provide anything like this?!

**Comment by IvanVorobei** [comment]
@FlorolF1 please, use delegate and method `didHide`

**Comment by FlorolF1** [comment]
i will give it a try, thanks

**Comment by IvanVorobei** [comment]
@FlorolF1 I will add this functionality soon

**Comment by FlorolF1** [comment]
There is a problem with notification. I doesn't change to "allowed" after allowing it. 
If i request notification permission during app start, SPPermissionDialog ist not updating the button.

I will use the last version as long you haven't fix the important things. 
But the layout look really nice, good work(y)

**Comment by IvanVorobei** [comment]
@FlorolF1 you tested in simulator?

**Comment by FlorolF1** [comment]
Nope, i tested it on a device.

I just translated you "old" version to swift 4.2 and tried all those functions. They are working.

**Comment by IvanVorobei** [comment]
@FlorolF1 in simulator notification not available for register by iOS. For testing notification permission - use real device only. In the previous version notification management same

**Comment by IvanVorobei** [comment]
@FlorolF1 I am intall 2.1.1 now for empty project, all work correctly. You allow notification permission is setting of project?

**Comment by FlorolF1** [comment]
I tested all those functions on a real device.
To reproduce the issue:
Go to AppDelegate: implement the following in "didFinishLaunchWithOptions"

        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge], completionHandler: {didAllow, error in
            if didAllow{
                
            }
            
        })
Allow Notification 
Next step: Open SPPermissionDialog and check the buttons.
I did this with Microphone,Camera and Library. They worked fine.
Notification didn't work.

**Comment by IvanVorobei** [comment]
@FlorolF1 
I see the bug. I will solve it. Thank!

**Comment by IvanVorobei** [comment]
@FlorolF1 I am find bug in your code.
I should use 

```
 UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge], completionHandler: {didAllow, error in
        if didAllow{
            
        }
        
    })

application.registerForRemoteNotifications() // IMPORTANT HERE LINE
```

**Comment by FlorolF1** [comment]
Declaration:
func registerForRemoteNotifications()

Discussion:
Call this method to initiate the registration process with Apple Push Notification service..

I don't use push notifications service in this application. But thank you (y)

**Comment by IvanVorobei** [comment]
@FlorolF1 

about push notifications service, sorry, but project check it only by register. This is due to the architecture of the project

About alert after denied permission (alert). I'm afraid I can not add it, because now after opening to the settings and allow permission, the application restarts. Previously, this was not and I believe that this will be inconvenient. I'm sorry.

I close this issue. Thanks for your feedback. Write if you have questions
