### ISSUE TITLE
How to customize icons?

### ISSUE THREAD

**Issue by emaddoma** [IvanVorobei/SPPermission#63]
Just updated to 2.1.1 and icon customization is missing

**Comment by IvanVorobei** [comment]
Good day!

Yes, customization icon disable
In the future I plan to add this functionality

**Comment by emaddoma** [comment]
That's a shame.  The previous version was great.

**Comment by IvanVorobei** [comment]
Dear friend, I find it strange to read. This project is absolutely free, but I get such criticism from you. Do not you think that I myself have to decide what to do? Learning that this is entirely my job.

I also want to note that you can safely use the old version, it is available. Successes

**Comment by emaddoma** [comment]
No criticism, friend.  It's just a little unusual to upgrade to a version with less features.  Keep up the good work!

**Comment by IvanVorobei** [comment]
I am uploading a new version where you can specify your icon

**Comment by IvanVorobei** [comment]
@emaddoma, I am publish new version `2.1.2`, now you can customise icon. See `SPPermissionDialogDataSource` and override function: 
```
func image(for permission: SPPermissionType) -> UIImage?
```

Return `nil` for default value

Thanks for your feedback

**Comment by furiosFast** [comment]
What should be the size of the icons?

**Comment by IvanVorobei** [comment]
icons draw by code. Not png or pdf file

**Comment by furiosFast** [comment]
I mean when using classic PNGs, through the function:
```
func image(for permission: SPPermissionType) -> UIImage? {
        switch permission {
            case .locationAlways, .locationWhenInUse, .locationWithBackground: return UIImage(named: "xxx")
            case .notification: return UIImage(named: "yyy")
            case .photoLibrary: return UIImage(named: "zzz")
        default: return nil
        }
    }
```

**Comment by IvanVorobei** [comment]
For png use min 200px
