### ISSUE TITLE
New layout only allows for very short descriptions for each permission

### ISSUE THREAD

**Issue by emaddoma** [IvanVorobei/SPPermission#65]
![simulator screen shot - iphone x - 2018-11-19 at 19 18 27](https://user-images.githubusercontent.com/12914515/48729639-01591200-ec30-11e8-94c3-145fd74c776d.png)

**Comment by IvanVorobei** [comment]
Good day! 

Yes, this is a special restriction to write compressed text, while preserving the visual component.

If you want to solve this problem, install the library manually and change a couple of lines of code.

If many users subscribe to this topic, I will create an adaptive system. While I'm not quite sure what is needed
