### ISSUE TITLE
Motion & VoiceRecognition permissions ?

### ISSUE THREAD

**Issue by francoisdeberry** [IvanVorobei/SPPermission#69]
Hello there,
Nice update since last time I came !
Would it be possible to add :
- Motion (Accelero, gyro...)
- VoiceRecognition
Thanks !

**Comment by IvanVorobei** [comment]
Good day, @francoisdeberry !
I am added it in new version soon 
Thanks for your feedback

**Comment by Legoless** [comment]
I would also need this @IvanVorobei. Could PR here, but you placed the entire source into a different repository, which makes collaboration harder.

**Comment by IvanVorobei** [comment]
@francoisdeberry I am added `speech` & `motion`. Update readme. All in new version `2.9`, please, update!
Sorry for delay
