### ISSUE TITLE
Ambiguous use of random

### ISSUE THREAD

**Issue by Eric0625** [IvanVorobei/SPPermission#70]
After I install this pod, the `Bool.random()` call makes compiler to gives an error: "Ambiguous use of random". 

It seems is of your extensions of bool in SPRandom.swift. Since swift 4.2 has already built those official random functions, maybe it's best to remove them.

**Comment by IvanVorobei** [comment]
Good idea! 
I am removed it. In new version (1-3 days)

But random func isset in other your pod

**Comment by IvanVorobei** [comment]
@Eric0625 I can not find official random func for swift 4. You can write it here?

**Comment by Eric0625** [comment]
It's in swift 4.2
![image](https://user-images.githubusercontent.com/18132007/49579624-beb16c80-f987-11e8-9bf9-f6df122daf02.png)

**Comment by IvanVorobei** [comment]
I am update pod and remove `Bool.random()`
Please, install last version `2.2.1`
