### ISSUE TITLE
wrong status for notifications

### ISSUE THREAD

**Issue by canaksoy** [IvanVorobei/SPPermission#77]
when notifications turned off in iOS settings SPPermission shows "allowed"

**Comment by IvanVorobei** [comment]
It happen because after turned off notification and return to app, button not reload. If you close modal controller and open again - permission for notification show "Allow"

All other permission after change permission in setting reload application.

**Comment by furiosFast** [comment]
use you the local notification?

**Comment by ThoseGuysInTown** [comment]
Are there plans to update the button states when coming back to the app from settings? With this it'd be great if the didAllow() delegate method was only called once the permission is actually allowed, not just when the button is taped.
