### ISSUE TITLE
Is locationWithBackground includes locationWhenInUse?

### ISSUE THREAD

**Issue by Yurssoft** [IvanVorobei/SPPermission#78]
Hello,
Imagine, in app is functionality that uses both `locationWithBackground` and `locationWhenInUse`. So, for in app map usage, we use `locationWhenInUse`, right? For background tracking, we use `locationWithBackground`. Now, the user sees permissions screen. User taps `locationWithBackground`. Therefore, now we have `locationWithBackground` in blue and `Allowed`. From my point of view, a user must see both `locationWithBackground` and `locationWhenInUse` in blue and `Allowed`. Am I right? Have I missed something?
Additionally, can we add `didHide(permissionsRequested: [SPPermissionType], permissionsAllowed: [SPPermissionType])`?
Thank in advance.

**Comment by Yurssoft** [comment]
Ask me :)

**Comment by IvanVorobei** [comment]
If you request `locationWithBackground` you don't need request `locationWhenInUse`. 

`locationWhenInUse ` not auto update after allowed `locationWithBackground`

Also I am fix small bug in permission, now if you check `locationWhenInUse ` and `locationWithBackground ` allowed, when in use permission will have style `allowed`

**Comment by Yurssoft** [comment]
If you request locationWithBackground you don't need request locationWhenInUse.
I thought about this, in fact we anyway have both locations. Thanks.
