### ISSUE TITLE
Change colour - Blue theme to Red or colour of choice

### ISSUE THREAD

**Issue by mcg95** [IvanVorobei/SPPermission#81]
Hi,

Is it possible to change the colours of the popup without using only blue? The application I am using has a red theme, and I think it would look better if everything was red or a shade of red rather than blue.

Thanks.

**Comment by IvanVorobei** [comment]
Thanks for your feedback, this development is already in process. A new version is coming soon.

**Comment by IvanVorobei** [comment]
I'll close the issue when I upload the update

**Comment by mcg95** [comment]
Thanks alot. Great Library btw.

**Comment by IvanVorobei** [comment]
I am added color scheme to new version `2.8`. Please, update and see Readme for customise colors

**Comment by IvanVorobei** [comment]
@mcg95, you pass `ColorSource` in `SPPermission.Dialog.request`?
