### ISSUE TITLE
[Suggestion/Request] - UNUserNotification Authorisation

### ISSUE THREAD

**Issue by Smiithy95** [IvanVorobei/SPPermission#84]
SPPermission works so well for all it's permissions, however is it possible to add support for UNUserNotifications with badges and alerts, and not just for the regular .notification (Remote Notifications)? 😄🤞🏼

**Comment by IvanVorobei** [comment]
I add differents case for local notification in next version. Thanks!

**Comment by IvanVorobei** [comment]
@Smiithy95 please, update to `2.9.2` version, I am fix it.
