### ISSUE TITLE
Bottom Comment Label Not Fit

### ISSUE THREAD

**Issue by muhasturk** [IvanVorobei/SPPermission#88]
SPPermissionDialogDataSource computed property bottomComment does not fit the current label maybe because of frame limitation.

#### Reproduce
```swift
    var bottomComment: String {
        return "Google ❤ Open Source. Google has 30 repositories available. Follow their code on GitHub."
    }
```

### Suspicious Code 

https://github.com/IvanVorobei/SPPermission/blob/fa766df34302fa0a6e0ebb1c65b29a97545f1080/Example/request-permission/Frameworks/SPPermission/Dialog/Controllers/SPPermissionDialogController.swift#L309-L311

### Result
![](https://i.ibb.co/p1nXwpT/Simulator-Screen-Shot-i-Phone-8-Plus-2019-02-05-at-10-52-43.png)

**Comment by IvanVorobei** [comment]
@muhasturk I am fix it in next version, maybe today

**Comment by IvanVorobei** [comment]
@muhasturk, I am update pod to version `3.0` and now fix it. Please, update. Thanks for your help and cool description of bug)
