### ISSUE TITLE
Cannot install with pods

### ISSUE THREAD

**Issue by smn-khan** [IvanVorobei/SPPermission#95]
No specification found for SPPermission

**Comment by IvanVorobei** [comment]
Please, take screenshoot if you podfile

**Comment by smn-khan** [comment]
https://www.dropbox.com/s/ewdv37urmx2eki4/Screenshot%202019-03-04%2011.30.23.png?dl=0

**Comment by IvanVorobei** [comment]
You try ‘pod update’?

**Comment by smn-khan** [comment]
No

**Comment by smn-khan** [comment]
should I?

**Comment by IvanVorobei** [comment]
Yes))) `pod install` allow use if you download pod local. Before install new pod you need call `pod update`.
